config/routes.rb
Rails.application.routes.draw do
  resources :movie_reviews
  get 'users/show'
  # get 'static_pages/home'
  root 'static_pages#home'
  devise_for :users
  resources :movies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
    has_one_attached :image
    
    has_many :movie_review, -> { order "created_at DESC"}
end

app/models/movie_review.rb
class MovieReview < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one_attached :avatar
  
  validates :name, presence: true
  validates :age, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
        def configure_permitted_parameters
            devise_parameter_sanitizer.permit :sign_up, keys: [:name, :age, :avatar]
            devise_parameter_sanitizer.permit :account_update, keys: [:name, :age, :avatar]
        end
end

app/controllers/movie_reviews_controller.rb
class MovieReviewsController < ApplicationController
  before_action :set_movie_review, only: [:show, :edit, :update, :destroy]

  # GET /movie_reviews
  # GET /movie_reviews.json
  def index
    @movie_reviews = MovieReview.all
  end

  # GET /movie_reviews/1
  # GET /movie_reviews/1.json
  def show
  end

  # GET /movie_reviews/new
  def new
    @movie_review = MovieReview.new
  end

  # GET /movie_reviews/1/edit
  def edit
  end

  # POST /movie_reviews
  # POST /movie_reviews.json
  def create
    @movie_review = MovieReview.new(movie_review_params)
    @movie_review.user_id = current_user.id

    respond_to do |format|
      if @movie_review.save
        url = "/movies/" + @movie_review.movie_id.to_s
        format.html { redirect_to url, notice: 'Movie review was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @movie_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movie_reviews/1
  # PATCH/PUT /movie_reviews/1.json
  def update
    respond_to do |format|
      if @movie_review.update(movie_review_params)
        format.html { redirect_to @movie_review, notice: 'Movie review was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie_review }
      else
        format.html { render :edit }
        format.json { render json: @movie_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movie_reviews/1
  # DELETE /movie_reviews/1.json
  def destroy
    @movie_review.destroy
    respond_to do |format|
      format.html { redirect_to movie_reviews_url, notice: 'Movie review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie_review
      @movie_review = MovieReview.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_review_params
      params.require(:movie_review).permit(:user_id, :movie_id, :review)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @movie_review = MovieReview.new
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:name, :length, :image, :detail)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movie_reviews_helper.rb
module MovieReviewsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">Home Page</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Movies List", movies_path, :class => "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Movie Reviews', movie_reviews_path, :class => "nav-link" %>
        </li>
      <% end%>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to current_user.name  , users_show_path, :class => "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to current_user.email, users_show_path, :class => "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "Sign out", destroy_user_session_path, method: :delete, :class => "nav-link"%>
        </li>
        <%else%>
        <li class="nav-item">
          <%= link_to "Sign in", new_user_session_path, :class => "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, :class => "nav-link" %>
        </li>
        <% end%>
      </ul>
    </form>
  </div>
</nav>
    <div class="container-fluid">
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/movie_reviews/_form.html.erb
<%= form_with(model: movie_review, local: true) do |form| %>
  <% if movie_review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie_review.errors.count, "error") %> prohibited this movie_review from being saved:</h2>

      <ul>
        <% movie_review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id,:class =>"form-control" %>
  </div>

  <div class="field">
    <%= form.label :movie_id %>
    <%= form.number_field :movie_id,:class =>"form-control"%>
  </div>

  <div class="field">
    <%= form.label :review %>
    <%= form.text_area :review,:class =>"form-control" %>
  </div>

  <div>
    <%= form.submit 'Submit', {:style => "margin : 20px 0;",:class => 'btn btn-primary'} %>
  </div>
<% end %>

app/views/movie_reviews/edit.html.erb
<h1 class="text-center">Editing Movie Review</h1>

<%= render 'form', movie_review: @movie_review %>

<%= link_to 'Show', @movie_review, :class => "btn btn-primary" %> |
<%= link_to 'Back', movie_reviews_path,{:style =>'margin: 20px 0;', :class => "btn btn-warning"} %>

app/views/movie_reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center">Movie Reviews</h1>
<%= link_to 'New Movie Review', new_movie_review_path, {:style =>'margin: 20px 0;', :class => "btn btn-outline-primary"} %>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th scope="col" class="text-center">User</th>
      <th scope="col" class="text-center">Movie</th>
      <th scope="col" class="text-center">Review</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movie_reviews.each do |movie_review| %>
      <tr>
        <td><%= movie_review.user_id %></td>
        <td><%= movie_review.movie_id %></td>
        <td><%= movie_review.review %></td>
        <td><%= link_to 'Show', movie_review %></td>
        <td><%= link_to 'Edit', edit_movie_review_path(movie_review) %></td>
        <td><%= link_to 'Destroy', movie_review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/movie_reviews/new.html.erb
<h1 class ="text-center">New Movie Review</h1>

<%= render 'form', movie_review: @movie_review %>

<%= link_to 'Back', movie_reviews_path %>

app/views/movie_reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @movie_review.user_id %>
</p>

<p>
  <strong>Movie:</strong>
  <%= @movie_review.movie_id %>
</p>

<p>
  <strong>Review:</strong>
  <%= @movie_review.review %>
</p>

<%= link_to 'Edit', edit_movie_review_path(@movie_review) ,:class => "btn btn-primary"%> |
<%= link_to 'Back', movie_reviews_path ,{:style =>'margin: 20px 0;', :class => "btn btn-warning"} %>

app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name,:class =>"form-control" %>
  </div>

  <div class="field">
    <%= form.label :length %>
    <%= form.number_field :length,:class =>"form-control" %>
  </div>
  
  <div class="field">
    <%= form.label :detail %>
    <%= form.text_area :detail,:class =>"form-control" %>
  </div>
  
  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image,:class =>"form-control-file" %><br>
  </div>
  
  <div class="d-flex justify-content-center"> 
    <div class="actions">
      <%= form.submit 'Submit', :class => 'btn btn-primary' %>
    </div>
  </div>
 
<% end %>

app/views/movies/edit.html.erb
<h1 class="text-center">Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie ,:class => "btn btn-primary" %> |
<%= link_to 'Back', movies_path,{:style =>'margin: 20px 0;', :class => "btn btn-warning"} %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center">Movies</h1>

<%= link_to 'New Movie', new_movie_path, {:style =>'margin: 20px 0;', :class => "btn btn-outline-primary"}%>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th scope="col" class="text-center">Name</th>
      <th scope="col" class="text-center">Length</th>
      <th scope="col" colspan="3" class="text-center">Action</th>
    </tr>
  </thead>

  <tbody >
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.name %></td>
        <td><%= movie.length %></td>
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/movies/new.html.erb
<h1 class="text-center">New Movie</h1>

<div class="card">
  <div class="card-header">
    Create New Movie
  </div>
  <div class="card-body">
    <%= render 'form', movie: @movie %>
  </div>
</div>


<%= link_to 'Back', movies_path,{:style =>'margin: 20px 0;', :class => "btn btn-warning"} %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>


<div class="d-flex justify-content-between">
  <div class="w-75">
    <h2 class="text-center">Movie Information</h2>
    <p>
      <strong>Name:</strong>
      <%= @movie.name %>
    </p>
    
    <p>
      <strong>Length in minutes:</strong>
      <%= @movie.length %>
    </p>
    
    <p>
      <strong>Detail:</strong>
      <%= @movie.detail %>
    </p>
    
    <strong>Image :</strong>
    <p class="text-center">
      <% if @movie.image.attached? %>
        <%= image_tag @movie.image %>
      <% end %>
    </p>
  </div>
  <div class="w-75" style ='margin: 20px 40px;'>
    <h2 class="text-center">Review Form</h2>
    <%= form_with(model: @movie_review, local: true) do |form| %>
      <div class= "field">
        <%= form.text_area :review, {:style =>'margin: 20px 0px;', :class =>"form-control", cols: "30", rows: "10"}  %>
        <%= form.hidden_field :movie_id, :value => @movie.id %>
      </div>
      <div class="actions">
        <%= form.submit 'Submit', :class => 'btn btn-primary' %>
      </div>
    <% end %>
    
    <h2 class="text-center">Review List</h2>
    <ul>
        <table class="table">
          <thead>
            <tr>
              <th scope="col">ID</th>
              <th scope="col">Name User</th>
              <th scope="col">Content</th>
            </tr>
          </thead>
          <tbody>
            <% @movie.movie_review.each do |movie_review|%>
              <tr>
                <td><%= movie_review.user_id %></td>
                <td><%= movie_review.user.name if movie_review.user%></td>
                <td><%= movie_review.review %></td>
              </tr>
            <% end %>
        </table>
    </ul>
  </div>
</div>





<%= link_to 'Edit', edit_movie_path(@movie),:class => "btn btn-primary" %> |
<%= link_to 'Back', movies_path,{:style =>'margin: 20px 0;', :class => "btn btn-warning"} %>

app/views/static_pages/home.html.erb
<h1 class = "text-center">Homepage</h1>
<img src="https://usustatesman.com/wp-content/uploads/2018/10/movie_reviewspooky.png" class="img-fluid" alt="Responsive image">

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1 class="text-center">Profile</h1>
<div class="d-flex flex-row ">
  <div class="card" style="width:500px" >
    <div class="card-header">
      <strong class="">Profile</strong>
    </div>
    <div class="card-body">
      <h4>Name :</h4>
      <%= @user.name %>
      
      <h4>Age :</h4>
      <%= @user.age %>
      
      <h4>Email :</h4>
      <%= @user.email %>
    </div>
  </div>
  <div style="padding: 0px 30px;">
    <p style="width: 70%; padding= 0px 30px;" class="text-center">
      <% if @user.avatar.attached? %>
        <%= image_tag(@user.avatar , class: 'img-fluid') %>
      <% end %>
    </p>
  </div>
</div>